Caught the exception
User-Defined Exception occurred